_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/home/niudt/u2seg_test/ckpts/cocotrain_300_0089999.pth"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
  BACKBONE:
    FREEZE_AT: 0
  SEM_SEG_HEAD:
    NUM_CLASSES: 54
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  FPN:
    NORM: "SyncBN"
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 80

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (30000, 40000)
  MAX_ITER: 45000
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  BASE_LR_MULTIPLIER: 4
  BASE_LR_MULTIPLIER_NAMES: [ 'roi_heads.mask_head.predictor', 'roi_heads.box_predictor.0.cls_score', 'roi_heads.box_predictor.0.bbox_pred', 'roi_heads.box_predictor.1.cls_score', 'roi_heads.box_predictor.1.bbox_pred', 'roi_heads.box_predictor.2.cls_score', 'roi_heads.box_predictor.2.bbox_pred' ]

INPUT:
  MIN_SIZE_TRAIN: (240, 320, 480, 640, 672, 704, 736, 768, 800, 1024)
  MAX_SIZE_TRAIN: 1333
  MASK_FORMAT: "bitmask"
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 0
  PRECISE_BN:
    ENABLED: True
    NUM_ITER: 200
  DETECTIONS_PER_IMAGE: 100

OUTPUT_DIR: ./output/eff_50per